language: c
os:
  - linux
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

git:
  - submodules: false

before_install:
  - git submodule update --init --recursive

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev
      - gcc
      - gcc-mingw-w64-x86-64
      - cmake
      - make

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
