language: c
os:
  - linux
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - gcc
      - gcc-mingw-w64-x86-64

script:
  - ./build-release.sh linux
  - ./build-release.sh windows