language: c
os:
  - linux
  - windows
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - gcc
      - gcc-mingw-w64-x86_64

script:
  - build.sh linux
  - build.sh windows