language: c
os:
  - linux
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libxcursor-dev
      - gcc
      - gcc-mingw-w64-x86-64

script:
  - bash build-release.sh linux
  - bash build-release.sh windows