language: c
os:
  - linux
  - windows
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - gcc
      - x86_64-w64-mingw32-gcc

script:
  - build.sh linux
  - build.sh windows