language: c
os:
  - linux
compiler:
  - c99-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev
      - gcc
      - gcc-mingw-w64-x86-64
      - make

script:
  - make tico
  - make tico PLATFORM=Windows